version: 0.0
os: linux
files:
  - source: /server
    destionation: /home/ec2-user/graphql/server
  - source: /web
    destionation: /home/ec2-user/graphql/web
hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
