# docker-compose.yml

version: "3.7"
services:
  postgres:
    build:
      context: postgres/.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lireddit
    ports:
      - "5432:5432"
    volumes:
      - web-db:/var/lib/postgresql/data

  server:
    build:
      context: server/.
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  web:
    build:
      context: web/.
    depends_on:
      - server
    ports:
      - "8080:80"

volumes:
  web-db:
